<template>
  <div class="flex justify-center flex-col items-center w-screen gap-10 ">
    <Navbar />
    <router-view />
  </div>
</template>
<script setup>
import Navbar from "components/Navbar.vue";
import PlaylistDetails from "./playlists/PlaylistDetails.vue";
import UserPlaylists from "./playlists/UserPlaylists.vue";
import ProfileCard from 'views/ProfileCard.vue'
import ProfileCardSkeleton from "./ProfileCardSkeleton.vue";
</script>
<style scoped>
.playlist-enter-active,
.playlist-leave-active {
  animation: blur-out 0.4s linear both
}

/* .playlist-enter {
  animation: blur-out 0.4s linear both
} */

.playlist-leave-to {
  animation: scale-down-center 0.4s;
}

/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.blur-out {
  animation: blur-out 0.4s linear both
}

@keyframes blur-out {
  0% {
    filter: blur(.01px);
  }

  100% {
    filter: blur(12px);
    opacity: 0
  }
}

/* ----------------------------------------------
  Generated by AnimatiSS
  Licensed under FreeBSD License
  URL: https://xsgames.co/animatiss
  Twitter: @xsgames_
---------------------------------------------- */

.scale-down-center {
  animation: scale-down-center 0.4s;
}

@keyframes scale-down-center {
  0% {
    transform: scale(1)
  }

  100% {
    transform: scale(.5)
  }
}
</style>
